# ==============================================================================
# SCRIPT 04: PREDICTIVE MAPPING AND CARTOGRAPHIC VISUALISATION (MULTI-YEAR LOOP)
# Project:  Accumulated Thermal Stress in Posidonia oceanica (Balearic Islands)
# Author:   Yeray Gonzalez-Marrero
# Purpose:  Generate five cartographic concepts of thermal impact and management
#           status for each target year. All output rasters and maps are masked
#           to the actual distribution of Posidonia oceanica (IDEIB Layer 2).
# Inputs:   outputs/rasters/dhd_posidonia_baleares.tif
#           outputs/tables/model_calibration_data.csv
#           outputs/tables/management_thresholds.xlsx
#           data/raw/posidonia_total_baleares_valida.geojson
#           models/modelo_scat_profundidad.rds  (or any model from Script 03)
# Outputs:  outputs/rasters/  (5 GeoTIFFs per year)
#           outputs/maps/      (5 PNG maps per year)
# ==============================================================================

# Delete workspace
rm(list = ls())


library(terra)
library(sf)
library(ggplot2)
library(dplyr)
library(tidyterra)
library(writexl)
library(mgcv)
library(scales)

cat("Starting spatial cartography module...\n")

# ==============================================================================
# SECTION 1: MODEL SELECTION FLAG
# ==============================================================================
# Set this flag to select which GAMM to use for the predictive impact map
# (Concept 3). Available options:
#   "Gaussian_Simple"   — Gaussian family, DHD only
#   "Gaussian_Depth"    — Gaussian family, DHD + depth
#   "Scat_Simple"       — Scaled-t family, DHD only
#   "Scat_Depth"        — Scaled-t family, DHD + depth (recommended)
model_flag <- "Scat_Depth"

model_files <- list(
  "Gaussian_Simple" = "models/modelo_gaussiano_simple.rds",
  "Gaussian_Depth"  = "models/modelo_gaussiano_profundidad.rds",
  "Scat_Simple"     = "models/modelo_scat_simple.rds",
  "Scat_Depth"      = "models/modelo_scat_profundidad.rds"
)

model_path <- model_files[[model_flag]]
if (is.null(model_path) || !file.exists(model_path)) {
  stop("Specified model file not found. Run Script 03 first or check the model_flag value.")
}

selected_model <- readRDS(model_path)
cat(sprintf("Predictive model loaded: %s\n", model_flag))

# ==============================================================================
# SECTION 2: LOAD BASE DATA AND CREATE OUTPUT DIRECTORIES
# ==============================================================================
dirs <- c("outputs/maps", "outputs/rasters")
for (d in dirs) if (!dir.exists(d)) dir.create(d, recursive = TRUE, showWarnings = FALSE)

dhd_raster  <- rast("outputs/rasters/dhd_posidonia_baleares.tif")
crs(dhd_raster) <- "EPSG:4326"

model_data  <- read.csv("outputs/tables/model_calibration_data.csv")
thresholds  <- readxl::read_xlsx("outputs/tables/management_thresholds.xlsx")

# Extract the two operational thresholds from the thresholds table
alert_threshold    <- thresholds$DHD_Value[thresholds$Category == "Alert Threshold (Green-Yellow)"]
critical_threshold <- thresholds$DHD_Value[thresholds$Category == "Critical Threshold (Yellow-Red)"]

# ==============================================================================
# SECTION 2b: LOAD AND PREPARE THE POSIDONIA SPATIAL MASK
# ==============================================================================
# The validated Posidonia distribution layer is generated by Script 01
# (Section 1b). It contains 32,839 polygons with repaired geometries (EPSG:4326).
# This mask restricts all output rasters and maps to cells where Posidonia
# oceanica is actually present, preventing misleading outputs over open water
# or land areas.
posidonia_path <- "data/raw/posidonia_total_baleares_valida.geojson"

if (!file.exists(posidonia_path)) {
  stop("Posidonia distribution layer not found at: ", posidonia_path,
       "\nRun Script 01 (01_data_acquisition.R) to download and repair the layer.")
}

cat("Loading and preparing Posidonia oceanica spatial mask...\n")

posidonia_sf <- st_read(posidonia_path, quiet = TRUE)

# Ensure WGS84 CRS
if (is.na(st_crs(posidonia_sf)) || st_crs(posidonia_sf)$epsg != 4326) {
  posidonia_sf <- st_transform(posidonia_sf, crs = 4326)
}

# Dissolve all polygons into a single geometry for efficient masking.
# sf_use_s2(FALSE) switches from the spherical S2 geometry engine to the
# planar GEOS engine, which is more robust for dissolving large numbers of
# small, densely packed polygons.
cat("  Dissolving Posidonia polygons (this may take a few seconds)...\n")
sf_use_s2(FALSE)
posidonia_union <- st_union(posidonia_sf)
sf_use_s2(TRUE)
posidonia_vect  <- vect(posidonia_union)

# Helper function: apply the Posidonia mask to a SpatRaster.
# Cells outside the Posidonia distribution are set to NA (transparent in maps).
# touches = TRUE retains cells that are only partially covered by the mask,
# which is important for narrow coastal meadow fringes at 0.05° resolution.
apply_posidonia_mask <- function(r, mask = posidonia_vect) {
  terra::mask(r, mask, touches = TRUE)
}

cat("[OK] Posidonia spatial mask prepared.\n")

# ==============================================================================
# SECTION 3: PUBLICATION-QUALITY GGPLOT2 THEME
# ==============================================================================
theme_publication <- theme_minimal(base_size = 12) +
  theme(
    plot.title       = element_text(size = 14, face = "bold"),
    plot.subtitle    = element_text(size = 12),
    axis.title       = element_text(size = 12, face = "bold"),
    axis.text        = element_text(size = 10),
    legend.title     = element_text(size = 11, face = "bold"),
    legend.text      = element_text(size = 10),
    legend.position  = "bottom",
    legend.key.width = unit(2, "cm")
  )

# ==============================================================================
# SECTION 4: MULTI-YEAR CARTOGRAPHIC LOOP
# ==============================================================================
years_to_map <- c(2022, 2024)
median_depth <- median(model_data$profundidad_m, na.rm = TRUE)

for (yr in years_to_map) {
  cat(sprintf("\n--- GENERATING CARTOGRAPHY FOR YEAR %d ---\n", yr))

  # Extract the DHD layer for the current year
  dhd_year <- dhd_raster[[paste0("DHD_", yr)]]

  # Fill coastal NA cells by interpolating from immediate neighbours.
  # Copernicus L4 SST products have NA values in nearshore cells due to
  # land contamination in the satellite retrieval algorithm. This step
  # ensures that coastal Posidonia meadows are not excluded from the maps.
  dhd_year <- focal(dhd_year, w = 3, fun = "mean",
                    na.policy = "only", na.rm = TRUE)

  # ============================================================================
  # CONCEPT 1: CATEGORICAL RISK MAP
  # ============================================================================
  # Classifies the marine space into three categories based solely on the
  # critical threshold (5.6 DHD):
  #   Class 1 (Green):  DHD <= 0 — no thermal stress
  #   Class 2 (Amber):  0 < DHD <= critical threshold — sub-lethal stress
  #   Class 3 (Red):    DHD > critical threshold — net regression zone
  # This binary-style map is most useful for rapid identification of areas
  # requiring immediate management intervention.
  cat("  -> Generating Map 1: Categorical Risk Map...\n")
  rcl_risk <- matrix(
    c(-Inf, 0,                  1,
      0.0001, critical_threshold, 2,
      critical_threshold, Inf,   3),
    ncol = 3, byrow = TRUE
  )
  risk_map      <- classify(dhd_year, rcl_risk)
  risk_map_mask <- apply_posidonia_mask(risk_map)

  writeRaster(risk_map_mask,
              sprintf("outputs/rasters/categorical_risk_map_%d.tif", yr),
              overwrite = TRUE)

  p_risk <- ggplot() +
    geom_spatraster(data = as.factor(risk_map_mask)) +
    scale_fill_manual(
      values       = c("1" = "#4CAF50", "2" = "#FFC107", "3" = "#F44336"),
      labels       = c("Stabilisation", "Chronic Stress", "Risk of Collapse"),
      na.translate = FALSE,
      name         = "Risk Level"
    ) +
    labs(
      title    = sprintf("Categorical Risk Map (%d)", yr),
      subtitle = sprintf("Based on critical threshold: %.1f DHD", critical_threshold),
      x = "Longitude", y = "Latitude"
    ) +
    coord_sf(expand = FALSE, crs = 4326) +
    scale_x_continuous(breaks = seq(1.0, 4.5, by = 0.5)) +
    theme_publication
  ggsave(sprintf("outputs/maps/map_1_categorical_risk_%d.png", yr),
         plot = p_risk, width = 8, height = 7, dpi = 300)

  # ============================================================================
  # CONCEPT 2: DISTANCE TO CRITICAL THRESHOLD MAP
  # ============================================================================
  # Computes the remaining thermal margin (in DHD) before each cell reaches
  # the critical threshold: margin = critical_threshold - DHD_accumulated.
  # Positive values indicate remaining buffer; negative values indicate the
  # threshold has already been exceeded.
  # This map is particularly informative for identifying areas that are not
  # yet in regression but are approaching the tipping point.
  cat("  -> Generating Map 2: Distance to Critical Threshold Map...\n")
  thermal_margin      <- critical_threshold - dhd_year
  names(thermal_margin) <- "DHD_Margin"
  thermal_margin_mask <- apply_posidonia_mask(thermal_margin)

  writeRaster(thermal_margin_mask,
              sprintf("outputs/rasters/thermal_margin_%d.tif", yr),
              overwrite = TRUE)

  p_margin <- ggplot() +
    geom_spatraster(data = thermal_margin_mask) +
    scale_fill_gradient2(
      low      = "#B71C1C",
      mid      = "#FFEB3B",
      high     = "#0D47A1",
      midpoint = 0,
      na.value = "transparent",
      name     = "Thermal Margin (DHD)"
    ) +
    labs(
      title    = sprintf("Distance to Critical Threshold (%d)", yr),
      subtitle = "Remaining thermal buffer before the physiological tipping point",
      x = "Longitude", y = "Latitude"
    ) +
    coord_sf(expand = FALSE, crs = 4326) +
    scale_x_continuous(breaks = seq(1.0, 4.5, by = 0.5)) +
    theme_publication
  ggsave(sprintf("outputs/maps/map_2_thermal_margin_%d.png", yr),
         plot = p_margin, width = 8, height = 7, dpi = 300)

  # ============================================================================
  # CONCEPT 3: PREDICTIVE IMPACT MAP (GAMM)
  # ============================================================================
  # Projects the expected interannual change in global shoot density (% yr-1)
  # across the entire archipelago using the calibrated GAMM. Depth is held
  # constant at the dataset median; the meadow random effect is excluded to
  # obtain population-level (marginal) predictions.
  # This map directly translates thermal stress into expected biological loss
  # or gain, making it the most ecologically informative output.
  cat("  -> Generating Map 3: Predictive Impact Map (GAMM)...\n")
  df_spatial <- as.data.frame(dhd_year, xy = TRUE, na.rm = TRUE)
  names(df_spatial)[3] <- "dhd_accumulated"

  df_spatial$id_pradera <- model_data$id_pradera[1]
  if ("profundidad_m" %in% names(selected_model$var.summary)) {
    df_spatial$profundidad_m <- median_depth
  }

  df_spatial$pred_delta <- predict(
    selected_model,
    newdata = df_spatial,
    type    = "response",
    exclude = "s(id_pradera)"
  )

  predictive_map      <- rast(df_spatial[, c("x", "y", "pred_delta")],
                              type = "xyz", crs = crs(dhd_year))
  predictive_map_mask <- apply_posidonia_mask(predictive_map)

  writeRaster(predictive_map_mask,
              sprintf("outputs/rasters/predictive_impact_map_%d.tif", yr),
              overwrite = TRUE)

  p_pred <- ggplot() +
    geom_spatraster(data = predictive_map_mask) +
    scale_fill_gradient2(
      low      = "#B71C1C",
      mid      = "#FFFDE7",
      high     = "#1B5E20",
      midpoint = 0,
      na.value = "transparent",
      name     = "\u0394 density (% yr\u207b\u00b9)"
    ) +
    labs(
      title    = sprintf("Predictive Impact Map — GAMM (%d)", yr),
      subtitle = sprintf("Model: %s", model_flag),
      x = "Longitude", y = "Latitude"
    ) +
    coord_sf(expand = FALSE, crs = 4326) +
    scale_x_continuous(breaks = seq(1.0, 4.5, by = 0.5)) +
    theme_publication
  ggsave(sprintf("outputs/maps/map_3_predictive_impact_%d.png", yr),
         plot = p_pred, width = 8, height = 7, dpi = 300)

  # ============================================================================
  # CONCEPT 4: DISCRETE MANAGEMENT TRAFFIC LIGHT
  # ============================================================================
  # Classifies the marine space into three discrete management zones using
  # both the alert and critical thresholds:
  #   Zone 1 (Green):  DHD < alert threshold — safe zone
  #   Zone 2 (Yellow): alert <= DHD < critical — sub-lethal stress zone
  #   Zone 3 (Red):    DHD >= critical — net regression zone
  # This is the most communicable map for policymakers and the general public,
  # as it directly conveys management urgency through a familiar colour code.
  cat("  -> Generating Map 4: Discrete Management Traffic Light...\n")
  rcl_traffic <- matrix(
    c(-Inf, alert_threshold,    1,
      alert_threshold, critical_threshold, 2,
      critical_threshold, Inf, 3),
    ncol = 3, byrow = TRUE
  )
  traffic_discrete      <- classify(dhd_year, rcl_traffic)
  traffic_discrete_mask <- apply_posidonia_mask(traffic_discrete)

  p_traffic_disc <- ggplot() +
    geom_spatraster(data = as.factor(traffic_discrete_mask)) +
    scale_fill_manual(
      values       = c("1" = "#4CAF50", "2" = "#FFEB3B", "3" = "#F44336"),
      labels       = c("Green Zone (Safe)", "Yellow Zone (Alert)", "Red Zone (Regression)"),
      na.translate = FALSE,
      name         = "Management Zone"
    ) +
    labs(
      title    = sprintf("Discrete Management Traffic Light (%d)", yr),
      subtitle = sprintf("Alert: %.1f DHD | Critical: %.1f DHD",
                         alert_threshold, critical_threshold),
      x = "Longitude", y = "Latitude"
    ) +
    coord_sf(expand = FALSE, crs = 4326) +
    scale_x_continuous(breaks = seq(1.0, 4.5, by = 0.5)) +
    theme_publication
  ggsave(sprintf("outputs/maps/map_4_discrete_traffic_light_%d.png", yr),
         plot = p_traffic_disc, width = 8, height = 7, dpi = 300)

  # ============================================================================
  # CONCEPT 5: CONTINUOUS MANAGEMENT TRAFFIC LIGHT (PURE DHD) — RECOMMENDED
  # ============================================================================
  # Retains the three-colour traffic light logic (Green / Yellow / Red) but
  # uses a continuous colour gradient within each zone to reflect true spatial
  # variability in thermal stress. This avoids the information loss inherent
  # in discrete classification (Concept 4), where cells with very different
  # DHD values appear identical.
  # The raw DHD raster is exported for use in GIS software (e.g., QGIS), where
  # the colour ramp can be further customised for publication-quality figures.
  cat("  -> Generating Map 5: Continuous Management Traffic Light (Pure DHD)...\n")

  dhd_year_mask <- apply_posidonia_mask(dhd_year)

  # Export the masked DHD raster (recommended for GIS-based cartography)
  writeRaster(dhd_year_mask,
              sprintf("outputs/rasters/continuous_traffic_light_DHD_%d.tif", yr),
              overwrite = TRUE)

  # Colour scale anchored to the actual data range of the masked raster
  max_dhd <- max(minmax(dhd_year_mask)[2], critical_threshold + 5, na.rm = TRUE)

  p_traffic_cont <- ggplot() +
    geom_spatraster(data = dhd_year_mask) +
    scale_fill_gradientn(
      colours = c("#1B5E20", "#8BC34A", "#FFEB3B", "#FF9800", "#F44336", "#b71c1c"),
      values  = rescale(c(0,
                          alert_threshold * 0.8,
                          alert_threshold,
                          (alert_threshold + critical_threshold) / 2,
                          critical_threshold,
                          max_dhd)),
      na.value = "transparent",
      name     = "Accumulated DHD"
    ) +
    labs(
      title    = sprintf("Continuous Management Traffic Light (%d)", yr),
      subtitle = sprintf("Spatial thermal variability (Green < %.1f < Yellow < %.1f < Red)",
                         alert_threshold, critical_threshold),
      x = "Longitude", y = "Latitude"
    ) +
    coord_sf(expand = FALSE, crs = 4326) +
    scale_x_continuous(breaks = seq(1.0, 4.5, by = 0.5)) +
    theme_publication
  ggsave(sprintf("outputs/maps/map_5_continuous_traffic_light_%d.png", yr),
         plot = p_traffic_cont, width = 8, height = 7, dpi = 300)
}

cat("\n[COMPLETE] Cartography module finished successfully.\n")
cat("All rasters and maps have been masked to the Posidonia oceanica distribution.\n")
