# ==============================================================================
# SCRIPT 05: OUTPUT RASTER VALIDATION AND INTEGRITY CHECK
# Project:  Accumulated Thermal Stress in Posidonia oceanica (Balearic Islands)
# Author:   Yeray Gonzalez-Marrero
# Purpose:  Perform a post-processing audit of the output rasters generated by
#           Scripts 02 and 04. Verifies that the DHD raster contains valid
#           continuous values and that the classified risk raster contains the
#           expected number of distinct classes. Diagnoses common GIS display
#           issues (e.g., single-colour rendering due to symbology settings).
# Inputs:   outputs/rasters/dhd_posidonia_baleares.tif
#           outputs/rasters/riesgo_posidonia_2023.tif
# ==============================================================================

# Delete workspace
rm(list = ls())


library(terra)

cat("--- RASTER OUTPUT INTEGRITY AUDIT ---\n")

# ==============================================================================
# STEP 1: Load the output rasters
# ==============================================================================
dhd_raster   <- rast("outputs/rasters/dhd_posidonia_baleares.tif")
risk_raster  <- rast("outputs/rasters/categorical_risk_map_2024.tif")

# ==============================================================================
# STEP 2: Inspect the continuous DHD raster (2024 layer)
# ==============================================================================
# Checks that the DHD values for 2023 fall within a physically plausible range.
# Values near zero indicate little or no thermal stress; very high values (> 50)
# are consistent with an extreme heatwave year.
cat("\n[1] CONTINUOUS DHD RASTER INSPECTION (2024):\n")
dhd_2024    <- dhd_raster[["DHD_2024"]]
dhd_summary <- global(dhd_2024, fun = c("min", "mean", "max"), na.rm = TRUE)
print(dhd_summary)

# ==============================================================================
# STEP 3: Inspect the classified risk raster (2023)
# ==============================================================================
# The risk raster should contain exactly three classes:
#   1 = Green  (stabilisation)
#   2 = Yellow (sub-lethal stress)
#   3 = Red    (net regression)
# If only one class is present, the classification thresholds may be misaligned
# with the actual DHD range for that year.
cat("\n[2] CLASSIFIED RISK RASTER INSPECTION (1 = Green, 2 = Yellow, 3 = Red):\n")
risk_frequencies <- freq(risk_raster)
print(risk_frequencies)

# ==============================================================================
# STEP 4: Health check — verify the expected number of classes
# ==============================================================================
n_classes <- nrow(risk_frequencies)

if (n_classes == 1) {
  cat(sprintf(
    "\n[WARNING] The risk raster contains only one class (value = %s).\n",
    risk_frequencies$value[1]
  ))
  cat("This indicates that all Balearic meadow cells in 2023 fall into a single risk category.\n")
  cat("Possible causes:\n")
  cat("  - The classification thresholds in Script 04 do not span the DHD range for 2023.\n")
  cat("  - The DHD raster for 2024 has an unexpectedly narrow value range.\n")
  cat("  - Re-check the threshold values in outputs/tables/management_thresholds.xlsx.\n")
} else {
  cat(sprintf(
    "\n[OK] Risk raster is valid: %d distinct classes detected.\n", n_classes
  ))
  cat("If the raster appears as a single colour in your GIS software, apply\n")
  cat("'Unique Values' symbology to render each class with a distinct colour.\n")
}
