# ==============================================================================
# SCRIPT: DATA QUALITY AUDIT — BIOLOGICAL AND MATHEMATICAL ANOMALY DETECTION
# Project:  Accumulated Thermal Stress in Posidonia oceanica (Balearic Islands)
# Author:   Yeray Gonzalez-Marrero
# Purpose:  Perform a systematic quality audit of the calibration dataset
#           generated by Script 03. Detects statistical outliers, base-density
#           artefacts, implausible growth rates, and unequal sampling intervals
#           that could bias the GAMM calibration. Exports a flagged watchlist
#           for manual review and a diagnostic QC plot.
# Input:    outputs/tables/model_calibration_data.csv
# Outputs:  outputs/tables/data_audit_watchlist.xlsx
#           outputs/plots/data_quality_audit_plot.png
# ==============================================================================

# Delete workspace
rm(list = ls())


library(dplyr)
library(writexl)
library(ggplot2)

# Load the calibration dataset produced by Script 03
if (!file.exists("outputs/tables/model_calibration_data.csv")) {
  stop("Calibration data not found. Run Script 03 first to generate the table.")
}
data <- read.csv("outputs/tables/model_calibration_data.csv")

cat(sprintf("--- STARTING FULL DATA QUALITY AUDIT (N = %d rows) ---\n", nrow(data)))

# ==============================================================================
# STEP 1: OUTLIER DETECTION VIA INTERQUARTILE RANGE (IQR)
# ==============================================================================
# Applies the standard Tukey fence rule: observations falling more than 1.5×IQR
# below Q1 or above Q3 are flagged as statistical outliers. These may represent
# genuine extreme events (e.g., post-heatwave mortality spikes) or data entry
# errors; manual inspection is required to distinguish between the two.
q1      <- quantile(data$delta_pct_yr, 0.25)
q3      <- quantile(data$delta_pct_yr, 0.75)
iqr_val <- q3 - q1
lower_fence <- q1 - (1.5 * iqr_val)
upper_fence <- q3 + (1.5 * iqr_val)

cat(sprintf("\n[IQR] Normal statistical range for density change: [%.2f%%, %.2f%%]\n",
            lower_fence, upper_fence))

# ==============================================================================
# STEP 2: BASE-DENSITY EFFECT DETECTION
# ==============================================================================
# Stations with very low initial shoot density (below the 15th percentile) are
# prone to inflated percentage change values: a small absolute change in a sparse
# meadow produces a disproportionately large % yr-1 value. These observations
# can exert high leverage on the GAMM and should be examined carefully.
low_density_threshold <- quantile(data$prev_density, 0.15, na.rm = TRUE)
cat(sprintf("[Base-density] 15th percentile of initial shoot density: %.1f shoots m\u207b\u00b2\n",
            low_density_threshold))

# ==============================================================================
# STEP 3: BUILD THE AUDIT WATCHLIST
# ==============================================================================
# Each row is assessed against four independent quality criteria. A row is
# included in the watchlist if it triggers at least one criterion. The watchlist
# is intended for manual expert review, not for automatic exclusion.
watchlist <- data %>%
  mutate(
    Flag_Statistical_Outlier   = delta_pct_yr > upper_fence | delta_pct_yr < lower_fence,
    Flag_Base_Density_Effect   = prev_density < low_density_threshold,
    Flag_Implausible_Growth    = delta_pct_yr > 50,   # > 50% yr-1 is biologically implausible
    Flag_Unequal_Sampling_Gap  = (anyo - prev_year) > 1   # non-consecutive sampling years
  ) %>%
  filter(
    Flag_Statistical_Outlier | Flag_Base_Density_Effect |
    Flag_Implausible_Growth  | Flag_Unequal_Sampling_Gap
  ) %>%
  select(
    id_estacion, isla, prev_year, anyo,
    prev_density, densidad_global_feixos_m2,
    delta_pct_yr, dhd_accumulated,
    Flag_Statistical_Outlier, Flag_Base_Density_Effect,
    Flag_Implausible_Growth, Flag_Unequal_Sampling_Gap
  ) %>%
  arrange(desc(abs(delta_pct_yr)))

cat(sprintf("\n[WARNING] %d rows flagged for manual review.\n", nrow(watchlist)))
write_xlsx(watchlist, "outputs/tables/data_audit_watchlist.xlsx")

# ==============================================================================
# STEP 4: HIGH-LEVERAGE POINT ANALYSIS (EXTREME DHD)
# ==============================================================================
# Observations with very high DHD values (> 35 degree-days) correspond to the
# most extreme thermal stress events in the dataset. These points carry high
# statistical leverage in the GAMM: they anchor the right-hand tail of the
# response curve and strongly influence the position of the critical threshold.
# This summary checks whether these high-leverage points are distributed across
# multiple islands (desirable) or concentrated in a single island (problematic).
leverage_summary <- data %>%
  filter(dhd_accumulated > 35) %>%
  group_by(isla) %>%
  summarise(
    N_Extreme_DHD_Points   = n(),
    Mean_Density_Change    = mean(delta_pct_yr)
  )

cat("\n--- HIGH-LEVERAGE POINT ANALYSIS (DHD > 35) BY ISLAND ---\n")
print(leverage_summary)

# ==============================================================================
# STEP 5: QUALITY CONTROL DIAGNOSTIC PLOT
# ==============================================================================
# Scatter plot of density change (% yr-1) against initial shoot density,
# coloured by whether the observation exceeds the acute stress threshold.
# IQR fences (red dashed lines) and the base-density threshold (blue dotted
# line) are overlaid to visually identify the flagged observations.
p_audit <- ggplot(data, aes(x = prev_density, y = delta_pct_yr)) +
  geom_point(
    aes(colour = dhd_accumulated > 28.7, shape = isla),
    size = 3, alpha = 0.7
  ) +
  geom_hline(
    yintercept = c(lower_fence, upper_fence),
    linetype = "dashed", colour = "red"
  ) +
  geom_vline(
    xintercept = low_density_threshold,
    linetype = "dotted", colour = "blue"
  ) +
  scale_colour_manual(
    values = c("TRUE" = "darkorange", "FALSE" = "darkgreen"),
    name   = "Critical thermal stress (DHD > 28.7)"
  ) +
  labs(
    title    = "Data Quality Audit: Annual Density Change vs. Initial Shoot Density",
    subtitle = "Red dashed lines: IQR fences | Blue dotted line: Low initial density threshold (base-density risk)",
    x        = "Initial shoot density (shoots m\u207b\u00b2)",
    y        = "Computed rate of change (% yr\u207b\u00b9)"
  ) +
  theme_minimal()

ggsave("outputs/plots/data_quality_audit_plot.png",
       plot = p_audit, width = 8, height = 6, dpi = 300)

cat("\n[COMPLETE] Audit finished.\n")
cat("Review 'outputs/tables/data_audit_watchlist.xlsx' for flagged observations.\n")
